=== MJsaka/DDType/src/resources/schema.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE schema [
<!ELEMENT schema (name,path,info,items)>
<!ELEMENT name (#CDATA)>
<!ELEMENT path (#CDATA)>
<!ELEMENT info (#CDATA)>
<!ELEMENT items (item+)>
<!ELEMENT item (name,path,info,items?)>
]>

=== MJsaka/DDType/src/resources/zm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schema SYSTEM "schema.dtd">

<schema>
	<name>zm</name>
	<path>zmpath</path>
	<info>zminfo</info>
	<items>
		<item>
			<name>zm1</name>
			<path>zmpath1</path>
			<info>zminfo1</info>
			<items>
				<item>
					<name>zm1.1</name>
					<path>zmpath1.1</path>
					<info>zminfo1.1</info>
				</item>
				<item>
					<name>zm1.2</name>
					<path>zmpath1.2</path>
					<info>zminfo1.2</info>
				</item>
			</items>
		</item>
		<item>
			<name>zm2</name>
			<path>zmpath2</path>
			<info>zminfo2</info>
		</item>
	</items>
</schema>
