=== MJsaka/DDType/resources/schema/dtd/schema.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT schema (name,path,units)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT units (unit+)>
<!ELEMENT unit (name,path,units?)>

=== MJsaka/DDType/resources/schema/def/zhengma.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schema SYSTEM "file:///usr/local/share/ddtype/schema/dtd/schema.dtd">

<schema>
	<name>郑码</name>
	<path>zhengma</path>
	<units>
		<unit>
			<name>字根</name>
			<path>zigen</path>
			<units>
				<unit>
					<name>笔画</name>
					<path>bihua</path>
				</unit>
				<unit>
					<name>第一主根</name>
					<path>zhugenyi</path>
				</unit>
				<unit>
					<name>第二主根</name>
					<path>zhugener</path>
				</unit>
				<unit>
					<name>副根</name>
					<path>fugen</path>
				</unit>
			</units>
		</unit>
		<unit>
			<name>单字</name>
			<path>danzi</path>
			<units>
				<unit>
					<name>一基根字</name>
					<path>yigenzi</path>
				</unit>
				<unit>
					<name>二基根字</name>
					<path>ergenzi</path>
				</unit>
				<unit>
					<name>三基根字</name>
					<path>sangenzi</path>
				</unit>
				<unit>
					<name>四基根字</name>
					<path>sigenzi</path>
				</unit>
				<unit>
					<name>多基根字</name>
					<path>duogenzi</path>
				</unit>
			</units>
		</unit>
		<unit>
			<name>词语</name>
			<path>ciyu</path>
			<units>
				<unit>
					<name>二字词</name>
					<path>erzici</path>
				</unit>
				<unit>
					<name>三字词</name>
					<path>sanzici</path>
				</unit>
				<unit>
					<name>多字词</name>
					<path>duozici</path>
				</unit>
			</units>
		</unit>
		<unit>
			<name>简码字</name>
			<path>jianmazi</path>
			<units>
				<unit>
					<name>一级简码字</name>
					<path>yijianzi</path>
				</unit>
				<unit>
					<name>二级简码字</name>
					<path>erjianzi</path>
				</unit>
				<unit>
					<name>三级简码字</name>
					<path>sanjianzi</path>
				</unit>
			</units>
		</unit>
		<unit>
			<name>简码词</name>
			<path>jianmaci</path>
			<units>
				<unit>
					<name>二级简码词</name>
					<path>erjianci</path>
				</unit>
				<unit>
					<name>三级简码词</name>
					<path>sanjianci</path>
				</unit>
			</units>
		</unit>
		<unit>
			<name>高频字词</name>
			<path>gaopinzici</path>
			<units>
				<unit>
					<name>高频字</name>
					<path>gaopinzi</path>
				</unit>
				<unit>
					<name>高频词</name>
					<path>gaopinci</path>
				</unit>
			</units>
		</unit>
	</units>
</schema>

=== MJsaka/DDType/resources/schema/def/zm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schema SYSTEM "file:///usr/local/share/ddtype/schema/dtd/schema.dtd">

<schema>
	<name>郑码</name>
	<path>zm</path>
	<units>
		<unit>
			<name>字根</name>
			<path>zg</path>
			<units>
				<unit>
					<name>主根</name>
					<path>zg</path>
				</unit>
				<unit>
					<name>副根</name>
					<path>fg</path>
				</unit>
			</units>
		</unit>
		<unit>
			<name>单字</name>
			<path>dz</path>
		</unit>
	</units>
</schema>
